name: pet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py311h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - certifi=2023.5.7=py311haa95532_0
  - cffi=1.15.1=py311h2bbff1b_3
  - cryptography=39.0.1=py311h21b164f_2
  - cuda-cccl=12.2.53=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - jinja2=3.1.2=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.6=py311hf62ec03_1
  - mkl_random=1.2.2=py311hf62ec03_1
  - numpy=1.25.0=py311hdab7c0b_0
  - numpy-base=1.25.0=py311hd01c5d8_0
  - openssl=3.0.9=h2bbff1b_0
  - pip=23.1.2=py311haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.3=he1021f5_1
  - pytorch=2.0.1=py3.11_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - setuptools=67.8.0=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.6.3=py311haa95532_0
  - urllib3=1.26.16=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==1.4.0
      # - airsim==1.8.1
      - ale-py==0.8.1
      - astunparse==1.6.3
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - flatbuffers==23.5.26
      - fonttools==4.40.0
      - gast==0.4.0
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.56.0
      - gymnasium==0.28.1
      - h5py==3.9.0
      - importlib-resources==5.12.0
      - jax==0.4.13
      - jax-jumpy==1.0.0
      - keras==2.12.0
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack-python==0.5.6
      - msgpack-rpc-python==0.4.1
      - networkx==3.1
      - oauthlib==3.2.2
      - opencv-contrib-python==4.8.0.74
      - opencv-python==4.8.0.74
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.3
      - pettingzoo==1.23.1
      - pillow==10.0.0
      - protobuf==4.23.3
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.5.0
      - pygments==2.15.1
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - scipy==1.11.1
      - shimmy==0.2.1
      - six==1.16.0
      - stable-baselines3==2.0.0
      - supersuit==3.8.0
      - sympy==1.12
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tinyscaler==1.2.6
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tornado==4.5.3
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - werkzeug==2.3.6
      - wrapt==1.14.1
prefix: C:\Users\lauqzz\AppData\Local\anaconda3\envs\pet
