name: deeprl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.0=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb82d6ee_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - cffi=1.15.1=py39h0878f49_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h21b164f_0
  - cuda-cccl=12.1.109=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.1.105=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=hd77b12b_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eigen=3.3.7=h59b6b97_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ffmpeg=4.2.2=he774522_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=pyhd8ed1ab_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.13.2=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hcbf5309_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.6.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.1=pyhd8ed1ab_0
  - krb5=1.19.4=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.3=h0ad7f3c_0
  - libxslt=1.1.37=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.6=py39hf11a4ad_1
  - mkl_random=1.2.2=py39hf11a4ad_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - opencv=4.6.0=py39hf11a4ad_3
  - openssl=1.1.1t=h2bbff1b_0
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39hd77b12b_0
  - pip=23.0.1=py39haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py39haa95532_0
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.16=h6244533_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32=305=py39h2bbff1b_0
  - pywinpty=2.0.10=py39h5da7b33_0
  - pyyaml=6.0=py39hb82d6ee_4
  - pyzmq=25.0.2=py39hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_8
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h2bbfb41_5
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.2=pyh08f2357_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.15.0=py39hcbf5309_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.6.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.2=pyhd8ed1ab_0
  - wheel=0.38.4=py39haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==1.4.0
      # - airsim==1.8.1
      - ale-py==0.7.4
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.1
      - certifi==2023.5.7
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - dm-tree==0.1.8
      - farama-notifications==0.0.4
      - filelock==3.12.0
      - flatbuffers==23.5.26
      - fonttools==4.39.4
      - gast==0.4.0
      - google-auth==2.19.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - gym==0.21.0
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - h5py==3.8.0
      - icecream==2.1.3
      - imageio==2.31.1
      - importlib-metadata==4.13.0
      - jax==0.4.11
      - jax-jumpy==1.0.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - lz4==4.3.2
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - marllib==1.0.3
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - ml-dtypes==0.1.0
      - mpi4py==3.1.4
      - mpmath==1.3.0
      - msgpack-python==0.5.6
      - msgpack-rpc-python==0.4.1
      - networkx==3.1
      - numpy==1.21.0
      - nvidia-pyindex==1.0.9
      - oauthlib==3.2.2
      - opencv-contrib-python==4.7.0.72
      - opencv-python==3.4.18.65
      - opt-einsum==3.3.0
      - pandas==2.0.2
      - pettingzoo==1.12.0
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyaudio==0.2.13
      - pyglet==2.0.7
      - pyparsing==3.0.9
      - pywavelets==1.4.1
      - ray==1.8.0
      - redis==4.5.5
      - requests-oauthlib==1.3.1
      - rich==13.4.1
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.10.1
      - setuptools==65.5.0
      - stable-baselines3==1.8.0
      - supersuit==3.2.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tifffile==2023.4.12
      - torch==1.9.0
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tornado==4.5.3
      - tqdm==4.65.0
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.4
      - wrapt==1.14.1
prefix: C:\Users\lauqzz\AppData\Local\anaconda3\envs\deeprl
